apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-env-scaledown
  namespace: eks-env-scaledown

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-env-scaledown
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "update"]

  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "update"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-env-scaledown
subjects:
  - kind: ServiceAccount
    name: eks-env-scaledown
    namespace: eks-env-scaledown
roleRef:
  kind: ClusterRole
  name: eks-env-scaledown
  apiGroup: rbac.authorization.k8s.io