apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-annotation
  labels:
    app: nginx-with-annotation
  annotations:
    eks-env-scaledown/startup-order: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-with-annotation
  template:
    metadata:
      labels:
        app: nginx-with-annotation
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 10Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
