# Simulate a pod which is provisioned by the Cronjob/Job which runs the eks-env-scaledown app
# We don't want the app to terminate itself via the K8s API when calling the terminateStandalonePods method
# It should ignore the pod based on a well-known app label

apiVersion: v1
kind: Pod
metadata:
  name: ignore-pod

  # This label excludes the pod from being terminated as long as it isn't part of a deployment or statefulset
  labels:
    app: eks-env-scaledown
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80