apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: httpd
  labels:
    app: httpd
  annotations:
    eks-env-scaledown/startup-order: "0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  serviceName: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: app
          image: httpd:2.4
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 10Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
